name: Tetragon Harden Action
description: Protect your GitHub Actions pipelines with Tetragon eBPF profiling
author: 'Niket Patel<patelniket@gmail.com>'
inputs:
  launchDelayTime:
    description: Delay in between launch of profiling tool and start of pipeline in seconds to accomodate all events capture
    default: '3'
    required: false  
  imageRegistry:
    description: Image Registry to pull image, oveerride to use internal private image registry
    default: 'quay.io'
    required: false
  tetragonImageTag:
    description: Tetragon Image Version - quay.io/cilium/tetragon-ci, override to use specific version
    default: 'latest'
    required: false  
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo $GITHUB_ACTION_REPOSITORY
        echo $GITHUB_ACTION_REF
        ls -al $GITHUB_WORKSPACE/../../_actions/$GITHUB_ACTION_REPOSITORY/
        ls -al $GITHUB_WORKSPACE/../../_actions/$GITHUB_ACTION_REPOSITORY/$GITHUB_ACTION_REF          
        docker run --name tetragon-container -d --rm --pid=host --cgroupns=host --privileged -v /sys/kernel/btf/vmlinux:/var/lib/tetragon/btf quay.io/cilium/tetragon-ci:latest
        docker exec tetragon-container tetra getevents -o compact >> ${{runner.temp}}/tetraevents &
        sleep 5

