name: PR Verify
on:
  pull_request:
    branches:
      - main 
permissions:
  contents: read
jobs:
  hardenprocess:
    runs-on: [ubuntu-latest]
    steps:
      # - name: Checkout codebase
      #   uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1

      # - name: Start Tetragon Scan
      #   uses: ./
      
      - name: Start Tetragon Scan
        uses: patelniketm/tetragon-harden-action@verify
      
      - name: Run Task
        run: |
          ls -al $GITHUB_WORKSPACE/../../_actions/$GITHUB_ACTION_REPOSITORY/
          ls -al $GITHUB_WORKSPACE/../../_actions/$GITHUB_ACTION_REPOSITORY/$GITHUB_ACTION_REF
          curl https://www.google.com
          echo "Hello" >> test.txt
      
      - name: Cleanup
        run: |
          sleep 2
          cat ${{runner.temp}}/tetraevents
          docker kill tetragon-container