name: PR Verify
on:
  pull_request:
    branches:
      - main 
permissions:
  contents: read
jobs:
  hardenprocess:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout codebase
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1  

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Start Tetragon Scan
        uses: ./
    
      - name: Run Task
        run: |
          curl https://www.google.com
          echo "Hello" >> test.txt